---
- name: install and configure IDM 12c products
  hosts: idm_servers
  become: yes
  become_user: root
  vars_files:
    - environments/{{ environment }}/inventories/vault.yml

  roles:
    - role: infra_pre_reqs
#    - role: jdk_setup
